from data import Location

# Questions that ask about the location itself
SPY_QUESTIONS = [
  "Is this place mobile or stationary?",
  "Would you typically find a lot of people here at once?",
  "Are there any uniforms commonly worn here?",
  "Is this place more commonly associated with entertainment or utility?",
  "What is the primary mode of communication here—face-to-face or through devices?",
  "Is there a high level of security in this place?",
  "Is the primary function of this place to serve a specific group of people or the general public?",
  "Would you expect to find medical staff here?",
  "Is this location often associated with travel?",
  "Is this place commonly found in urban areas?",
  "Would people typically need a ticket or special permission to enter here?",
  "Is there a religious or spiritual aspect associated with this place?",
  "Does this place have strict schedules or timetables?",
  "Is the environment here controlled or affected by natural elements?",
  "Is the atmosphere here usually quiet or noisy?",
  "Is this place likely to be a destination for tourists?",
  "Would people come here to learn or be educated?",
  "Does this place require specialized training or expertise to work in?",
  "Is this place primarily used for leisure or work?",
  "Would you find this place in a war or combat scenario?"
]

# Questions that ask about the person being here
NONSPY_QUESTIONS = [
  "What is the first thing you notice when you arrive here?",
  "What kind of footwear is most appropriate here?",
  "Is this a place you would bring children?",
  "How would you describe the temperature here?",
  "What is a typical sound you might hear here?",
  "Would you typically visit this place alone or with others?",
  "How often do you think people come here in a week?",
  "Is there any specific behavior expected in this place?",
  "What is a typical item you might carry with you here?",
  "Are there any particular smells you associate with this place?",
  "How much time do people usually spend here?",
  "Is this a place where you would see a lot of technology?",
  "Would you describe this place as bustling or more laid-back?",
  "What is the typical lighting like here?",
  "Are there specific types of vehicles you would see near this place?",
  "Is this place generally associated with a particular group of people or profession?",
  "What kind of conversations do you hear here?",
  "Is this a place you would visit for a specific purpose or for leisure?",
  "How would you describe the seating arrangements here?",
  "Is there anything you would not want to forget to bring when coming here?"
]

GENERIC_QUESTIONS = [
    "When was the last time you were here?",
    "How often do you find yourself in this situation?",
    "What is the first thing you usually do when you get here?",
    "How long do you typically stay when you are here?",
    "Who else is usually here when you come?",
    "What time of day do you prefer to be here?",
    "How did you end up here the first time?",
    "Is there anything unique about the atmosphere here?",
    "What is something people generally do here?",
    "What would make this experience better for you?",
    "What is the most common thing people talk about when they are here?",
    "How do you feel when you are in a place like this?",
    "Do you ever come here with others or alone?",
    "How do you usually get here?",
    "What would you miss most if you could not come here anymore?",
    "Is there a particular reason you come here?",
    "What is the most unexpected thing you have seen or done here?",
    "How do you pass the time when you are here?",
    "What is the best part about being here, in your opinion?",
    "How do you usually feel when you leave this place?"
]


# Examples answers for the question: "How often do you come here?"
EXAMPLE_ANSWER = {
    Location.AIRPLANE: "A few times a year",
    Location.BANK: "Not often",
    Location.BEACH: "Every once in a while",
    Location.BROADWAY_THEATER: "Not often",
    Location.CASINO: "Not often",
    Location.CATHEDRAL: "Not often",
    Location.CIRCUS_TENT: "Not often",
    Location.CORPORATE_PARTY: "Never",
    Location.CRUSADER_ARMY: "Never",
    Location.DAY_SPA: "Not often",
    Location.EMBASSY: "Never",
    Location.HOSPITAL: "Not often",
    Location.HOTEL: "A few times a year",
    Location.MILITARY_BASE: "Not often",
    Location.MOVIE_STUDIO: "A few times a year",
    Location.OCEAN_LINER: "Never",
    Location.PASSENGER_TRAIN: "Not often",
    Location.PIRATE_SHIP: "Never",
    Location.POLAR_STATION: "Never",
    Location.POLICE_STATION: "Not often",
    Location.RESTAURANT: "A few times a month",
    Location.SCHOOL: "Not often",
    Location.SERVICE_STATION: "Not often",
    Location.SPACE_STATION: "Never",
    Location.SUBMARINE: "Never",
    Location.SUPERMARKET: "A few times a month",
    Location.UNIVERSITY: "Every day",
}

EXAMPLE_QUESTIONS = [
    "How often do you come here?",
    "What is there to eat here?",
    "Have you been here before?",
    "Would this location smell good?",
    "Is this place kid-friendly?",
    "Is there a lot of noise in this place?",
    "What time of day is the busiest here?",
    "Do you need a reservation to visit?",
    "What kind of clothing do people typically wear here?",
    "How far is this location from the nearest public transportation?",
    "Are most people here happy?",
]


EXAMPLE_BAD_ANSWER = {
    Location.AIRPLANE: "Every day",
    Location.BANK: "Never",
    Location.BEACH: "Every day",
    Location.BROADWAY_THEATER: "Every day",
    Location.CASINO: "Several times a week",
    Location.CATHEDRAL: "Several times a day",
    Location.CIRCUS_TENT: "Once a week",
    Location.CORPORATE_PARTY: "A few times a month",
    Location.CRUSADER_ARMY: "A few times a year",
    Location.DAY_SPA: "Several times a day",
    Location.EMBASSY: "Every week",
    Location.HOSPITAL: "Every day",
    Location.HOTEL: "Never",
    Location.MILITARY_BASE: "Daily",
    Location.MOVIE_STUDIO: "Never",
    Location.OCEAN_LINER: "A few times a week",
    Location.PASSENGER_TRAIN: "A few times a week",
    Location.PIRATE_SHIP: "A few times a week",
    Location.POLAR_STATION: "A few times a year",
    Location.POLICE_STATION: "A few times a week",
    Location.RESTAURANT: "Never",
    Location.SCHOOL: "Never",
    Location.SERVICE_STATION: "Daily",
    Location.SPACE_STATION: "A few times a year",
    Location.SUBMARINE: "Weekly",
    Location.SUPERMARKET: "Never",
    Location.UNIVERSITY: "Never",
}

